spring:
  application:
    name: bigbread-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bigbread}
    username: ${DB_USERNAME:bigbread}
    password: ${DB_PASSWORD:bigbread}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
